<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\JobPortal.Shared\JobPortal.Shared.csproj" />
    <ProjectReference Include="..\LoginManagement.DTO\LoginManagement.DTO.csproj" />
    <ProjectReference Include="..\LoginManagement.Handler\LoginManagement.Handler.csproj" />
  </ItemGroup>

</Project>
