<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoginManagement.AggregateRoot\LoginManagement.AggregateRoot.csproj" />
    <ProjectReference Include="..\LoginManagement.DTO\LoginManagement.DTO.csproj" />
    <ProjectReference Include="..\LoginManagement.Repository\LoginManagement.Repository.csproj" />
  </ItemGroup>

</Project>
